### ISSUE TITLE
docker container not building anymore

### ISSUE THREAD

**Issue by prieux** [AirVantage/tv-dashboards#8]
Might not been related to latest change:
```
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>

    import packaging.version

ImportError: No module named packaging.version

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-L3U5XM/simplegeneric/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4tnCFF-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-L3U5XM/simplegeneric
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc6 in position 31: ordinal not in range(128)
The command '/bin/sh -c apt-get update &&     apt-get install --fix-missing -y python-pip wget git vim unzip python-dev openssl ca-certificates &&     pip install --upgrade ipython python-dateutil pytz jira jinja2 tornado Flask requests &&     cd /usr/local/share/ca-certificates/ && wget http://ca.anyware-tech.com/anyware-tech.crt &&     update-ca-certificates &&     useradd engtv -U -s /bin/false &&     mkdir -p /home/engtv/static/ &&     mkdir -p /home/engtv/www' returned a non-zero code: 1
docker@default:/home/workspace/tv-dashboards$
```

**Comment by prieux** [comment]
* Applied solution found [here](http://stackoverflow.com/questions/42068069/unable-to-install-python-module) for image based on minideb (not required when using alpine based image)
* Tested new container based on [minideb](https://github.com/bitnami/minideb), image size is 150 MB (vs 524 MB for debian jessie based) ✔️ 
* Tested new container based on [python alpine](https://github.com/docker-library/python/tree/master/2.7/alpine), image size is 97 MB ✔️

**Comment by prieux** [comment]
fix successfully deployed on frtls-retd.anyware
